name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and run
        run: |
          docker-compose build
          docker-compose up -d

      - name: Send signal
        run: |
          docker ps -a
          docker kill -s SIGTERM node
          docker-compose down
          docker logs node
